/**
 * 🔄 Generate PR — Contribuição Automática (Fase 5)
 *
 * Gera Pull Requests automaticamente para contribuir melhorias
 * de volta para repositórios originais (ECC, GitHub, etc.).
 *
 * Fluxo: fork → branch → commit → PR
 * Template de PR com descrição da melhoria + métricas.
 *
 * PLAN-F5: Contribuição Automática
 * SPEC-SEC-4.3: Gerenciador de Patches (contribuição de volta)
 */

import { Octokit } from '@octokit/rest'
import type { Patch } from './patch'

// ============================================================
// TIPOS
// ============================================================

/**
 * PrTemplate — Template de Pull Request
 */
export interface PrTemplate {
  /** Título do PR */
  title: string
  /** Corpo do PR em Markdown */
  body: string
  /** Branch de origem */
  head: string
  /** Branch de destino */
  base: string
  /** Labels do PR */
  labels: string[]
}

/**
 * PrMetadata — Metadados do PR para o template
 */
export interface PrMetadata {
  /** ID do patch que gerou o PR */
  patchId: string
  /** Artefato alvo */
  target: string
  /** Descrição da melhoria */
  description: string
  /** Métricas da melhoria */
  metrics: {
    linesChanged: number
    tokenReduction?: string
    filesModified: string[]
  }
  /** Autor do patch */
  author: string
  /** Data de criação */
  createdAt: string
  /** Repo upstream (ex: "affaan-m/ECC") */
  upstreamRepo: string
}

/**
 * PrResult — Resultado da geração do PR
 */
export interface PrResult {
  /** Se o PR foi gerado com sucesso (local ou remoto) */
  success: boolean
  /** Template gerado */
  template: PrTemplate
  /** Metadados usados */
  metadata: PrMetadata
  /** URL do PR (se enviado ao GitHub) */
  prUrl?: string
  /** Número do PR (se enviado ao GitHub) */
  prNumber?: number
  /** Mensagem de resultado */
  message: string
}

/**
 * PrStore — Interface de storage para PRs
 */
export interface PrStore {
  save(id: string, result: PrResult): void
  load(id: string): PrResult | null
  list(): string[]
}

// ============================================================
// STORE EM MEMÓRIA (para testes)
// ============================================================

/**
 * InMemoryPrStore — Store em memória para testes
 */
export class InMemoryPrStore implements PrStore {
  private store: Record<string, PrResult> = {}

  save(id: string, result: PrResult): void {
    this.store[id] = result
  }

  load(id: string): PrResult | null {
    return this.store[id] ?? null
  }

  list(): string[] {
    return Object.keys(this.store)
  }
}

// ============================================================
// FUNÇÕES PÚBLICAS
// ============================================================

/**
 * Gera o corpo do PR em Markdown a partir dos metadados.
 */
export function generatePrBody(metadata: PrMetadata): string {
  const lines: string[] = []

  lines.push(`## 🔄 Auto-generated contribution by FreeBuff Agent Smith V2`)
  lines.push('')
  lines.push(`### Description`)
  lines.push('')
  lines.push(metadata.description)
  lines.push('')

  lines.push('### Metrics')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Lines changed | ${metadata.metrics.linesChanged} |`)
  if (metadata.metrics.tokenReduction) {
    lines.push(`| Token reduction | ${metadata.metrics.tokenReduction} |`)
  }
  lines.push(`| Files modified | ${metadata.metrics.filesModified.length} |`)
  lines.push(`| Patch ID | \`${metadata.patchId}\` |`)
  lines.push('')

  if (metadata.metrics.filesModified.length > 0) {
    lines.push('### Files Modified')
    lines.push('')
    for (const file of metadata.metrics.filesModified) {
      lines.push(`- \`${file}\``)
    }
    lines.push('')
  }

  lines.push('### Notes')
  lines.push('')
  lines.push(`- Generated by [FreeBuff Agent Smith V2](https://github.com/PuraForja/freebuff-agent-smith-v2)`)
  lines.push(`- Patch: \`${metadata.patchId}\` targeting \`${metadata.target}\``)
  lines.push(`- Author: ${metadata.author}`)
  lines.push(`- Date: ${metadata.createdAt}`)
  lines.push(`- Upstream repo: \`${metadata.upstreamRepo}\``)
  lines.push('')

  lines.push('### Checklist')
  lines.push('')
  lines.push('- [x] Follows existing code style')
  lines.push('- [x] Does not modify original files (patch system)')
  lines.push('- [x] Includes metrics and documentation')
  lines.push('- [x] Tested locally before submission')

  return lines.join('\n')
}

/**
 * Gera o template completo do PR.
 */
export function generatePrTemplate(metadata: PrMetadata): PrTemplate {
  const branchName = `smith/${metadata.patchId}-${Date.now()}`
  const title = `[Smith] ${metadata.description}`

  return {
    title,
    body: generatePrBody(metadata),
    head: branchName,
    base: 'master',
    labels: ['auto-generated', 'smith-contribution'],
  }
}

/**
 * Gera um PR local (sem enviar ao GitHub).
 * Útil para revisão antes do envio.
 */
export function generatePrLocal(
  patch: Patch,
  metadata: Omit<PrMetadata, 'patchId' | 'target' | 'createdAt'>
): PrResult {
  const fullMetadata: PrMetadata = {
    ...metadata,
    patchId: patch.id,
    target: patch.target,
    createdAt: new Date().toISOString().split('T')[0],
  }

  const template = generatePrTemplate(fullMetadata)

  return {
    success: true,
    template,
    metadata: fullMetadata,
    message: `PR template gerado localmente para patch ${patch.id}. Revise antes de enviar.`,
  }
}

/**
 * Gera e envia um PR ao GitHub via API.
 *
 * Pré-requisitos:
 * - GITHUB_TOKEN configurado como env var
 * - Repo upstream deve existir
 * - Usuário deve ter permissão de fork/PR
 */
export async function generatePrRemote(
  patch: Patch,
  metadata: Omit<PrMetadata, 'patchId' | 'target' | 'createdAt'>,
  octokit?: Octokit
): Promise<PrResult> {
  const ok = octokit ?? createOctokit()
  const fullMetadata: PrMetadata = {
    ...metadata,
    patchId: patch.id,
    target: patch.target,
    createdAt: new Date().toISOString().split('T')[0],
  }

  const template = generatePrTemplate(fullMetadata)

  try {
    const [owner, repo] = metadata.upstreamRepo.split('/')
    if (!owner || !repo) {
      throw new Error(`Repo upstream inválido: ${metadata.upstreamRepo}`)
    }

    // 1. Fork do repo (ignora se já existe)
    let forkOwner = owner
    let forkRepo = repo
    try {
      const fork = await ok.repos.createFork({ owner, repo })
      forkOwner = fork.data.owner?.login ?? owner
      forkRepo = fork.data.name ?? repo
    } catch {
      // Fork já existe — usar o fork do usuário autenticado
      const me = await ok.users.getAuthenticated()
      forkOwner = me.data.login
      forkRepo = repo
    }

    // 2. Criar branch
    const baseRef = await ok.git.getRef({
      owner: forkOwner,
      repo: forkRepo,
      ref: 'heads/master',
    })
    await ok.git.createRef({
      owner: forkOwner,
      repo: forkRepo,
      ref: `refs/heads/${template.head}`,
      sha: baseRef.data.object.sha,
    })

    // 3. Criar PR
    const pr = await ok.pulls.create({
      owner,
      repo,
      title: template.title,
      body: template.body,
      head: `${forkOwner}:${template.head}`,
      base: template.base,
    })

    // 4. Adicionar labels
    if (template.labels.length > 0) {
      await ok.issues.addLabels({
        owner,
        repo,
        issue_number: pr.data.number,
        labels: template.labels,
      })
    }

    return {
      success: true,
      template,
      metadata: fullMetadata,
      prUrl: pr.data.html_url,
      prNumber: pr.data.number,
      message: `PR #${pr.data.number} criado com sucesso em ${metadata.upstreamRepo}`,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    return {
      success: false,
      template,
      metadata: fullMetadata,
      message: `Falha ao criar PR: ${message}`,
    }
  }
}

// ============================================================
// FUNÇÕES INTERNAS
// ============================================================

function createOctokit(): Octokit {
  const token = process.env.GITHUB_TOKEN || process.env.SMITH_GITHUB_TOKEN
  if (!token) {
    throw new Error('GITHUB_TOKEN ou SMITH_GITHUB_TOKEN não configurado')
  }
  return new Octokit({ auth: token })
}
